name: Deploy static site with API Key

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create config.js with API Key
        run: |
          echo "const apiKey = '${{ secrets.APIKEY }}';" > scripts/config.js
          echo "export default apiKey;" >> scripts/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
